### ISSUE TITLE
Component error: indego - Integration 'indego' not found.

### ISSUE THREAD

**Issue by mirkin1993** [jm-73/Indego#128]
Today I updated my Home Assistant version to 2021.6.2 and the indego integration gives the following error: `Component error: indego - Integration 'indego' not found.`

In the logfile I found: `2021-06-05 11:08:25 ERROR (SyncWorker_1) [homeassistant.loader] The custom integration 'indego' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details`

**Comment by mirkin1993** [comment]
Added the version manually to the file from the repo.

**Comment by pinsdorf** [comment]
I had the same issue. @eavanvalkenburg kindly fixed this in PR #124 and @jm-73 merged it into the code base. Thanks for this!

Unfortunately, there is no tagged release yet, that contains this change. Last release is 3.7 from 4 Aug 2020. As a result the fix is not present when you install / had installed this component via HACS. Please tag the fix as 3.8 so that people get an update notification in HACS. Thanks.

**Comment by simonk1969** [comment]
> Added the version manually to the file from the repo.

Are you able to advise what you needed to add and to what file as there doesn't seem to be a fix released yet.

Thanks :-)

**Comment by Shamshala** [comment]
@simonk1969 [https://github.com/jm-73/Indego/issues/121#issuecomment-853398229](https://github.com/jm-73/Indego/issues/121#issuecomment-853398229)

**Comment by pinsdorf** [comment]
Open file `custom_components/indego/manifest.json` in HomeAssistant's file editor.

Change the file so that its end looks like this:
```json
  ...
  "requirements": ["pyIndego==2.0.26"],
  "version": "3.7.1" 
}
```
The `version` line is the new entry, which causes the issue. HomeAssistant requires it since version 2021.6. Don't forget the comma at the end of the preceding line. Restart HomeAssistant (or reload the Indego integration).
