### ISSUE TITLE
awaiting async_forward_entry_setups

### ISSUE THREAD

**Issue by SeriousPat** [jm-73/Indego#170]
Setup failed for custom integration indego: Unable to import component: Exception importing custom_components.indego
18:42:32 – (FEHLER) setup.py

Unexpected exception importing component custom_components.indego
18:42:32 – (FEHLER) indego (benutzerdefinierte Integration)

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 18:42:17 (1 occurrences)
Last logged: 18:42:17

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for homematicip_local using this method at custom_components/homematicip_local/__init__.py, line 54: hass.config_entries.async_setup_platforms(config_entry, HMIP_LOCAL_PLATFORMS)

**Comment by jm-73** [comment]
Hi!

What version off HA are you running?
What version of the integration are you running?
When did the problem start?
Do you get the error every time you start HA, or just now and then?
Do your credentials work in the Bosch App?
Have you tried to reinstall the integration?
Have you tried to disable all other integrations?
Have you tried with a fresh install of HA?

After you answer this questions, you can send me log files in a PM in the Discord channel. Enable the debug mode and do a fresh restart when collecting logs to send to me. Otherwise I cannot find what I am looking for.

Kind regards Jens

**Comment by SeriousPat** [comment]
What version off HA are you running?
2023.2.5 (HASS OS VM)

What version of the integration are you running?
4.0.2

When did the problem start?
Since using the integration

Do you get the error every time you start HA, or just now and then?
After every HA Update, the restart after.
(I will test of this occours on forst boot)

Do your credentials work in the Bosch App?
Yes

Have you tried to reinstall the integration?
No

Have you tried to disable all other integrations?
No

Have you tried with a fresh install of HA?
No (The HA installation is quite new)

**Comment by SeriousPat** [comment]
I will first check my Login. You can close this error if you want. I will make a new one if its nessesary.
I need some weeks to check this. (At this moment, my Indego app on my mobile device doesnt work for some reason)
