### ISSUE TITLE
Login with SingleKey ID Error

### ISSUE THREAD

**Issue by Burbacottero** [jm-73/Indego#180]
Unfortunately, the integration no longer works with the current login (single key).
Any ideas please?

**Comment by jm-73** [comment]
If you have a problem, you have to give details:
Version of HA
Version of Indego Integration
When did it work the last time
What error message do you get
Turn on logging and paste the exact error message

Or else the answer will be 42...

**Comment by sytchi** [comment]
Aren't you trying to log-in with the current stable version? If yes, it's outdated. The working log-in solution is present in the beta version. 5.1.0.

**Comment by Burbacottero** [comment]
Ok, i solved using version 5.1.0 and the chrome plugin for login. Thanks

**Comment by jm-73** [comment]
Ok good

**Comment by hs06** [comment]
Hi jm-73,
I also have an issue with the login. I do get the outh redirect to the Bosch site. on Safari/Mac it will say "invalid link". On Safari/Mac it will not load. On Safari/iOS it will jump into the Bosch App.
I had added the "Indego:" on my config.yaml. The jump-to-oauth-website happens when I want to add the integration. (popup: visit website).

Versions are: Indego integration 5.1.0 via HACS

Home Assistant 2023.5.4
Supervisor 2023.04.1
Operating System 10.1
Frontend 20230503.3 - latest

I can get more logs if needed. Weird thing: No logs apart from the warning "custom integration" in the HA logs. Don't know if that's how it should be - would expect some startup messages, but I'm only two days into HA so far.

Thanks a lot for any hints!
Hendrik

**Comment by hs06** [comment]
Ah, it was this nasty Single Key ID OAuth Flow.

I read around a little and found issue #171 with this thread https://github.com/jm-73/Indego/issues/171
and figured out what was wrong. With the Chrome Extension linked there I was able to get the token from the redirect into HA. The extension is here: https://github.com/sander1988/Indego/blob/master/chrome-extension.zip

Thanks a lot to the awesome community! :-)
